In [2]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a*b)
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)

[1 4 9]
<class 'numpy.ndarray'>
1
3
int64


In [11]:
a = np.array([i for i in range(9)]).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
print(np.zeros((2,2))) #Tuple
print(np.ones((2,2)))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [17]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a - b)
print(a*2)
print(a**2)
print(a * b)

[0 0 0 0]
[2 4 6 8]
[ 1  4  9 16]
[ 1  4  9 16]


In [32]:
a = np.arange(10)
print(a[5:])
print(a[-1])
print(a[::])
print(a[::-1])

[5 6 7 8 9]
9
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [33]:
def f(x,y):
    return x+y

print(np.fromfunction(f, (4,5)))


[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]
